In [1]:
# load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import  seaborn as sns
from  pandas.plotting import scatter_matrix

In [11]:
df = pd.read_csv('/home/susan/battery_materials_ml/data/insertion_electrodes.csv')
df.head()
data = df.copy()
print(df['battery_type'].unique())
print(data["thermo_type"].isna().sum())

['insertion']
4103

In [3]:
print(data.columns)
print()
print("="*50)
data.head(5)

Index(['builder_meta', 'battery_type', 'material_ids', 'thermo_type',
       'battery_formula', 'working_ion', 'num_steps', 'max_voltage_step',
       'last_updated', 'framework', 'framework_formula', 'elements',
       'nelements', 'chemsys', 'formula_anonymous', 'warnings',
       'formula_charge', 'formula_discharge', 'max_delta_volume',
       'average_voltage', 'capacity_grav', 'capacity_vol', 'energy_grav',
       'energy_vol', 'fracA_charge', 'fracA_discharge', 'stability_charge',
       'stability_discharge', 'id_charge', 'id_discharge', 'host_structure',
       'adj_pairs', 'entries_composition_summary', 'electrode_object'],
      dtype='object')

==================================================

,builder_meta,battery_type,material_ids,thermo_type,battery_formula,working_ion,num_steps,max_voltage_step,last_updated,framework,...,fracA_charge,fracA_discharge,stability_charge,stability_discharge,id_charge,id_discharge,host_structure,adj_pairs,entries_composition_summary,electrode_object
0,{'emmet_version': '0.86.4rc1.dev71+g64b11f337....,insertion,['mp-aaaaaovi' 'mp-aaacsdct'],NaN,Cs0-3Ac,Cs,1,0.0,2025-09-19 09:41:17.571210+00:00,"[('Ac', 1.0)]",...,0.0,0.750000,0.020409,0.535925,mp-aaaaaovi,mp-aaacsdct,"{'@module': 'pymatgen.core.structure', '@class...","[{'formula_charge': 'Ac', 'formula_discharge':...","{'all_formulas': array(['Ac', 'Cs3Ac'], dtype=...",{'@module': 'pymatgen.apps.battery.insertion_b...
1,{'emmet_version': '0.86.4rc1.dev71+g64b11f337....,insertion,['mp-aaaaaovi' 'mp-aaacpiss'],NaN,Ca0-3Ac,Ca,1,0.0,2025-09-19 09:42:20.982522+00:00,"[('Ac', 1.0)]",...,0.0,0.750000,0.020409,0.057262,mp-aaaaaovi,mp-aaacpiss,"{'@module': 'pymatgen.core.structure', '@class...","[{'formula_charge': 'Ac', 'formula_discharge':...","{'all_formulas': array(['Ac', 'Ca3Ac'], dtype=...",{'@module': 'pymatgen.apps.battery.insertion_b...
2,{'emmet_version': '0.86.4rc1.dev71+g64b11f337....,insertion,['mp-aaacpjjn' 'mp-aaacsist'],NaN,Li0-1CsAcO3,Li,1,0.0,2025-09-19 09:43:22.301779+00:00,"[('Cs', 1.0), ('Ac', 1.0), ('O', 3.0)]",...,0.0,0.166667,0.219559,0.300647,mp-aaacpjjn,mp-aaacsist,"{'@module': 'pymatgen.core.structure', '@class...","[{'formula_charge': 'CsAcO3', 'formula_dischar...","{'all_formulas': array(['CsAcO3', 'CsLiAcO3'],...",{'@module': 'pymatgen.apps.battery.insertion_b...
3,{'emmet_version': '0.86.4rc1.dev71+g64b11f337....,insertion,['mp-aaaaaaeu' 'mp-aaacpmmb'],NaN,Na0-3Ag,Na,1,0.0,2025-09-19 09:42:57.716505+00:00,"[('Ag', 1.0)]",...,0.0,0.750000,0.003609,0.045182,mp-aaaaaaeu,mp-aaacpmmb,"{'@module': 'pymatgen.core.structure', '@class...","[{'formula_charge': 'Ag', 'formula_discharge':...","{'all_formulas': array(['Na3Ag', 'Ag'], dtype=...",{'@module': 'pymatgen.apps.battery.insertion_b...
4,{'emmet_version': '0.86.4rc1.dev71+g64b11f337....,insertion,['mp-aaaaaaeu' 'mp-aaabxgwx'],NaN,Li0-3Ag,Li,1,0.0,2025-09-19 09:43:24.372752+00:00,"[('Ag', 1.0)]",...,0.0,0.750000,0.003609,0.000000,mp-aaaaaaeu,mp-aaabxgwx,"{'@module': 'pymatgen.core.structure', '@class...","[{'formula_charge': 'Ag', 'formula_discharge':...","{'all_formulas': array(['Li3Ag', 'Ag'], dtype=...",{'@module': 'pymatgen.apps.battery.insertion_b...

In [4]:
# EDA data 
data.drop(columns=['builder_meta','battery_type', 'thermo_type' ,'id_charge', 'id_discharge', 'host_structure',
       'adj_pairs', 'entries_composition_summary', 'last_updated','electrode_object'], errors ='ignore', inplace=True)
print()
print("="*50)

==================================================

In [10]:
print(data.info())
print()
print("="*50)
data[["battery_formula", "nelements", "chemsys"]].head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4103 entries, 0 to 4102
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   material_ids         4103 non-null   object
 1   battery_formula      4103 non-null   object
 2   working_ion          4103 non-null   object
 3   num_steps            4103 non-null   int64
 4   max_voltage_step     4103 non-null   float64
 5   framework            4103 non-null   object
 6   framework_formula    4103 non-null   object
 7   elements             4103 non-null   object
 8   nelements            4103 non-null   int64
 9   chemsys              4103 non-null   object
 10  formula_anonymous    4103 non-null   object
 11  warnings             4103 non-null   object
 12  formula_charge       4103 non-null   object
 13  formula_discharge    4103 non-null   object
 14  max_delta_volume     4103 non-null   float64
 15  average_voltage      4103 non-null   float64
 16  capacity_grav        4103 non-null   float64
 17  capacity_vol         4103 non-null   float64
 18  energy_grav          4103 non-null   float64
 19  energy_vol           4103 non-null   float64
 20  fracA_charge         4103 non-null   float64
 21  fracA_discharge      4103 non-null   float64
 22  stability_charge     4103 non-null   float64
 23  stability_discharge  4103 non-null   float64
dtypes: float64(11), int64(2), object(11)
memory usage: 769.4+ KB
None

==================================================

  battery_formula  nelements  chemsys
0         Cs0-3Ac          1       Ac
1         Ca0-3Ac          1       Ac
2     Li0-1CsAcO3          3  Ac-Cs-O
3         Na0-3Ag          1       Ag
4         Li0-3Ag          1       Ag
5       Mg5-149Ag          1       Ag
6         Mg0-5Ag          1       Ag
7         Mg2-3Ag          1       Ag
8      Mg0-0.33Ag          1       Ag
9     Na0-2AgAsF6          3  Ag-As-F